### PR TITLE
SeaMonkey support

### PR DESCRIPTION
**Pull request by IsaacSchemm**
If you would like to support SeaMonkey, these are the only changes necessary to do so.

* Full "Components.utils" used instead of "Cu" shortcut - same with Ci, Cc, and so on
* Some text from aboutCertError.dtd copied into private.dtd (aboutCertError.dtd has a different location in SeaMonkey so we can't use it in both)
* Findbar reference stored in gFireIE.findbar, because SeaMonkey (as far as I know) does not have a global variable that refers to it
* Added SeaMonkey XUL paths to chrome.manifest
* Added SeaMonkey to install.rdf

### CODE REVIEW

**Comment by patwonder** [comment]
Wow, thank you! Great work! I'll test it out as soon as possible.

I have a question though. You mentioned using full "Components.utils" instead of Cu - as far as I remember most of the JS source files have the shortcuts defined at the beginning of the file, is it still mandatory to write the full name?

**Comment by IsaacSchemm** [comment]
If they're defined at the top of the file, then it shouldn't be necessary. I actually forgot to check.
Should I make another pull request without those changes?

**Comment by patwonder** [comment]
No need to create another pull request. You can just update your branch to revert these changes.

**Comment by patwonder** [comment]
I've tested the code on latest SeaMonkey release and it works quite well! Most of the main features of Fire IE works under SeaMonkey and it's pretty much ready for everyday use. However, I see some problems, too.

The first is a bunch of errors in hooking some of the Firefox functions, which SeaMonkey doesn't have:
hook error

Do you know any alternatives to these functions in SeaMonkey? Especially **getShortcutOrURIAndPostData** since we have a feature that depends on it (Always use current engine for URLs typed in URL bar).

The second problem is that auto-switch does not work in private browsing windows. I did some debugging and it seems **Utils.getTabFromBrowser** is not working properly:

```JavaScript
  getTabFromBrowser: function(browser)
  {
    ...
    
    let windows = Utils.generatorFromEnumerator(Services.wm.getEnumerator("navigator:browser"),
      Ci.nsIDOMWindow);
    for (let window in windows)
    {
      let tab = getTabFromBrowserWithinWindow(browser, window);
      if (tab) return tab;
    }
    return null;
  },
```
The statement `Services.wm.getEnumerator("navigator:browser")` seems to only return non-private windows. Do you know any workarounds?

**Comment by IsaacSchemm** [comment]
I'm not sure about how to get the private windows. This is the first time I've done any real work with the Mozilla framework.

SeaMonkey has promiseShortcutOrURI (in https://dxr.mozilla.org/comm-central/source/suite/browser/navigator.js), but I can't seem to get it hooked properly - it doesn't seem like the hook is getting called.

      //not working?
      if (typeof(promiseShortcutOrURI) !== "undefined")
        HM.hookCodeTail("promiseShortcutOrURI", function(ret) {
          let promise = ret;
          if (!promise) return;
          let newPromise = promise.then(function(data)
          {
            if (data.length > 0 && data[0])
            {
              data[0] = gFireIE.getHandledURL(data[0]);
            }
            return data;
          });
          return RET.modifyValue(newPromise);
        });

SeaMonkey doesn't to navigate to a page when you drop something onto the URL bar, so I wouldn't worry about gURLBar.

#ev-button is the equivalent of #identity-box, but it works slightly differently - I might look into it later.

**Comment by IsaacSchemm** [comment]
I got #security-button working. Part of that was putting a hook into the BrowserPageInfo function for when the security tab is aclled for but the IE engine is active - this might affect Firefox too, but I don't think it would break anything.

**Comment by IsaacSchemm** [comment]
I should mention that none of these changes break Fire-IE in Firefox (at least they shouldn't - you might want to test that).
You might want to merge these changes in but remove SeaMonkey from the install.rdf. That way, SeaMonkey users who run the add-on through the add-on converter (http://addonconverter.fotokraina.com/) will get something more functional than they would now.

**Comment by patwonder** [comment]
I've tested on Firefox and it seems nothing is broken. I think the commits are safe to merge.
Thank you for the great work!

**Pull request merged**
